### PR TITLE
Release v5.1

### PR DESCRIPTION
**Pull request by jfmdev**
New features:

- #5 | Improve import/export/edit feature on Options page.
- #6 | Add additional options for update settings on Options page.
- #7 | Add Mixpanel and track clicks on menu items.
- #77 | Add support for Microsoft Edge.

Enhancements:

- Store both timestamp and error message when refreshing the configuration.
- Replace "About" tab with an external link.
- #4 | Minor customizations on Bootstrap theme.
- #11 | Add command to zip 'dist' folder.
- #12 | Gray out disable groups instead of line-through.
- #21 | Format response from POST requests.
- #22 | Fix branding of Search Providers.
- #47 | Add icons to all buttons in Options page.

Bugs fixed:

- Update "Last config update" label after a failed refresh (on Options page).
- Don't show success message if decryption failed.
- #20 | Improve call for open Options page.
- #81 | Open Welcome page only when installing.
- #84 | Make zip content top-level.
- #86 | When importing a "Search Options" all values should be overridden.

Internal changes:

- Add Webpack to minify code.
- #1 | Use Yarn to download dependencies and Webpack to bundle them.
- #10 | Add Prettier (and fix ESLint warnings).
- #14 | Move settings.json file back to root (was moved to 'src/' folder when adding webpack).
- #15 | Replace "gibberish-aes" by "aes-js".
- #17 | Refactor code from "utils.js" (and add ESLint).
- #30 | Enable 'split chunks' on Webpack for prevent duplicated code.
- #32 | Define URLs as constants.
- #40 | Re-enable "no-undef" and "no-useless-escape" lint rules.
- #54 | Allow to update URLs and Labels from Search Providers.
- #58 | Add unit testing.
- #59 | Add E2E testing.
- #63 | Add unit tests for "ConfigFile.updateNow".
- #64 | Add unit test for "ConfigFile.generateJSON" method.
- #65 | Add E2E test for migration script.
- #66 | Add unit tests for "ConfigFile.parseJSONFile" method.
- #67 | Add unit tests for "ConfigFile.sanitizeSettings" method.
- #68 | Add E2E test for POST handler.
- #69 | Add unit tests for contextual menu creation.
- #70 | Add unit tests for contextual menu clicks.

-----

To do before merge:

- [x] Update version (on both package and manifest).
- [x] Run unit tests.
- [x] Run E2E tests.
- [x] QA testing.

-----

**Note:** when releasing this new version on Chrome, the checkbox "User activity" (on "Privacy settings" > "Data usage") will need to be checked (on the Chrome Web Store Developer Dashboard).

### CODE REVIEW

**Comment by jfmdev** [comment]
Testing plan
========

## 1. Installation

### 1.1 Upgrading (Chrome only)

Settings from previous version (v5.0) of the extension should be migrated when upgrading (to 5.1).
For test this: install v5.0; go to the Options page of the extension and change the settings; upgrade to v5.1; go to the Options page and check that settings are the same.

> Please note that you must modify all settings (i.e. override most values on tabs Settings, Search Providers, NetWitness, Carbon Black and RSA Security) to be sure that all settings are being migrated correctly.

### 1.2 First install (Chrome and Edge)

**1.2.1** Settings should be populated with data from `settings.json` if file on Configuration URL is unreachable.

> For test this: modify the "https://raw.githubusercontent.com/AdvancedThreatAnalytics/threat-analytics-search/main/settings.json" value from settings.json to a bogus URL; install the extension and verify (on the Options page and on the Contextual Menu) that the default values (defined on `settings.json`) have been loaded.

**1.2.2** Settings should be override with values read from the file defined by the Configuration URL.

> Note that currently both the files from https://raw.githubusercontent.com/AdvancedThreatAnalytics/threat-analytics-search/main/settings.json and `settings.json` contains almost the same data, so for test this you can: change the values from settings.json; install the extension; verify (on the Options page and on the Contextual Menu) that the values from the URL have been used.

## 2. Basic Settings

> For test this, go to the "Settings" tab from the Options page from the Extension.

### 2.1 Configuration File Options

**2.1.1** Clicking "Enable groups" should automatically add/remove groups from the contextual menu.

**2.1.2** Settings should be refreshed with external files.

> As described above, just create another JSON configuration file (with different values from the current default values), put that URL on "Configuration URL", click "Refresh now" and verify that the configuration has been udpated with the values of the file.

**2.1.3** Settings should be refreshed with external encripted files.

> For test this: create a copy of `settings.json`, modify some of his values, then encrypt the file and publish it somewhere; put the URL of the encripted file on "Configuration URL", check "Encrypted" and put somePassword on "Encryption Key"; finally click "Refresh now" and check that settings are updated.

## 2.3 Import/Export

**2.3.1** Changing the settings should modify the JSON textarea.

> For test this: go to the Settings tab, change some settings, and check that the JSON value on the textarea has been automatically updated to reflect this change; then go to the Search Providers tab, change some values, and then go to the Settings tab and check that the JSON has been automatically updated; repeat the same for tabs Security Analytics, NetWitness and Carbon Black.

**2.3.2** JSON files should be imported correctly.

For test this: go to the Settings tab, change values from search providers, config, rsa, nwi and cbc, click import and check that all values have been imported correctly.

## 3. Search Providers

**3.1** Changing the order on the Options page should change the order on the contextual menu.

**3.2** Disabling/enabling a search provider on the Options page should add/remove his item from the contextual menu.

**3.3** Modifying the name and URL of a search provider should update his corresponding item on the contextual menu.

**3.4** If you add a new search provider, it should be appended to the contextual menu.

**3.5** If you remove a search provider, it should be removed from the contextual menu.

## 4. Groups

**4.1** Clicking on a group should tabs for all search providers on that group (please test this for all three groups).

**4.2** If you rename or enable/disable groups, the change should be automatically reflected on the context menu.

**Comment by tim-kodirov** [comment]
## 1
- [x] Upgrading keeps settings from previous version
- [ ] Settings should be overriden with values read from the file defined by the Configuration URL.
        

> Event if configuration URL is valid, all settings are taken from "settings.json", and not from URL file

## 2
- [x] Clicking "Enable groups" should automatically add/remove groups from the contextual menu.
- [ ] Settings should be refreshed with external files.

> Clicking "Update now" doesn't update with the new values

- [x] Changing the settings should modify the JSON textarea.
- [ ] JSON files should be imported correctly.

> Importing a file behaves weirdly. Providers are not updated, queries for special providers are appended, not replaced

**Comment by Saidmurod1996** [comment]
**3. Search Providers**

- [x] 3.1 Changing the order on the Options page should change the order on the contextual menu.

- [x] 3.2 Disabling/enabling a search provider on the Options page should add/remove his item from the contextual menu.

- [x] 3.3 Modifying the name and URL of a search provider should update his corresponding item on the contextual menu.

- [x] 3.4 If you add a new search provider, it should be appended to the contextual menu.

- [x] 3.5 If you remove a search provider, it should be removed from the contextual menu.

**4. Groups**

- [x] 4.1 Clicking on a group should tabs for all search providers on that group (please test this for all three groups).

- [x] 4.2 If you rename or enable/disable groups, the change should be automatically reflected on the context menu.

LGTM from my side

**Comment by Saidmurod1996** [comment]
@jfmdev all three test fails Temur says might be because we are first setting settings.json values and after getting result from configurationUrl we are trying to replace it, but "mergeSearchProviders" is merge by default, it's not overriding.

**Comment by jfmdev** [comment]
@tim-kodirov @Saidmurod1996 Sorry, I just have explained myself better on the testing plan:

**1.2.2** Settings should be ~override~ _updated_ with values read from the file defined by the Configuration URL.

> E.g. if the external files defines new Search Providers or new Queries for CBC / NWI / RSA, these values should be added; and if the group names have changed, then it should also be updated.  
> Note that, _by default_, search providers and query are "merged" and only group names are "overridden" when updating (while ignoring all other changes on the external file).

**2.1.2** Settings should be refreshed with external files _according to options selected on "Merge Settings Option" panel_.

**2.3.2** JSON files should be imported correctly _(overriding **all** current values)_. ➡️ This must be fixed on #86

**Comment by jfmdev** [comment]
@tim-kodirov I'll re-open #65 since the tests are failing (probably due to the changes done by #81)

**Comment by Saidmurod1996** [comment]
Checked that above test failures are fixed. LGTM

**Review by Saidmurod1996 — APPROVED** [review]

**Pull request merged**
