### PR TITLE
Issue #140 | Migrate Manage Groups to Svelte

### PR DESCRIPTION
**Pull request by pushpendraKh**
fixes: #140
resolves: PIX-648

### CODE REVIEW

**Comment by Saidmurod1996** [comment]
Pressing label used to enable/disable the checkbox, but now it's not working like that

**Comment by pushpendraKh** [comment]
@Saidmurod1996 Actually numbers were there from start but they were not displaying (was a bug).

**Comment by Saidmurod1996** [comment]
LGTM

**Review by jfmdev — CHANGES_REQUESTED** [review]
Merge conflicts 🙁

**Pull request merged**
